import { makeStyles } from '@fluentui/react-components';

// ─── Palette: clinical teal, Excel-native neutrals ───────────────────────────
// Primary teal #107C6C — professional, clinical, distinct from AI purple
// Neutrals drawn from Fluent Design: warm grays that feel native to Office

export const useSpcStyles = makeStyles({
  panel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    overflowY: 'auto',
    height: '100%',
    fontFamily: "'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    backgroundColor: '#ffffff',
  },
  section: {
    padding: '14px 16px',
    borderBottom: '1px solid #e8e6e3',
  },
  sectionLabel: {
    fontSize: '11px',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: '#8e8e96',
    marginBottom: '10px',
  },
  dataSourceEmpty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    padding: '28px 16px',
    textAlign: 'center',
  },
  dataSourceIcon: {
    width: '42px',
    height: '42px',
    borderRadius: '8px',
    backgroundColor: '#e8f5f2',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#107C6C',
    fontSize: '20px',
  },
  dataSourceHint: {
    fontSize: '12px',
    color: '#8e8e96',
    lineHeight: '1.4',
  },
  dataSourceBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  address: {
    flex: 1,
    fontSize: '11.5px',
    fontFamily: "'Cascadia Code', 'SF Mono', 'Consolas', monospace",
    color: '#5c5c65',
    backgroundColor: '#f6f6f8',
    padding: '6px 10px',
    borderRadius: '4px',
    border: '1px solid #e8e6e3',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  colRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    marginBottom: '2px',
  },
  colLabel: {
    fontSize: '11.5px',
    fontWeight: '600',
    color: '#5c5c65',
    minWidth: '14px',
  },
  chartTypeRow: {
    display: 'flex',
    gap: '3px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  chartBtn: {
    padding: '5px 10px',
    borderRadius: '4px',
    border: '1px solid #d0ceca',
    backgroundColor: '#ffffff',
    color: '#5c5c65',
    fontSize: '12px',
    fontWeight: '600',
    fontFamily: 'inherit',
    cursor: 'pointer',
    letterSpacing: '0.3px',
    textTransform: 'uppercase',
    transition: 'all 0.12s ease',
    '&:hover': {
      borderTopColor: '#107C6C',
      borderRightColor: '#107C6C',
      borderBottomColor: '#107C6C',
      borderLeftColor: '#107C6C',
      color: '#0A6B5C',
      backgroundColor: '#e8f5f2',
    },
  },
  chartBtnActive: {
    backgroundColor: '#107C6C',
    borderTopColor: '#0A6B5C',
    borderRightColor: '#0A6B5C',
    borderBottomColor: '#0A6B5C',
    borderLeftColor: '#0A6B5C',
    color: '#ffffff',
    boxShadow: '0 1px 2px rgba(16,124,108,0.25)',
  },
  chartBtnMore: {
    padding: '5px 10px',
    borderRadius: '4px',
    border: '1px dashed #c8c6c4',
    backgroundColor: 'transparent',
    color: '#8e8e96',
    fontSize: '11px',
    fontWeight: '500',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 0.12s ease',
    '&:hover': {
      borderTopColor: '#107C6C',
      borderRightColor: '#107C6C',
      borderBottomColor: '#107C6C',
      borderLeftColor: '#107C6C',
      color: '#0A6B5C',
    },
  },
  chartMorePanel: {
    display: 'flex',
    gap: '3px',
    flexWrap: 'wrap',
    marginTop: '6px',
    paddingTop: '8px',
    borderTop: '1px solid #e8e6e3',
  },
  settingsToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '500',
    color: '#5c5c65',
    fontFamily: 'inherit',
    '&:hover': {
      color: '#107C6C',
    },
  },
  settingsPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '10px',
    padding: '12px',
    backgroundColor: '#f6f6f8',
    borderRadius: '6px',
    border: '1px solid #e8e6e3',
  },
  settingRow: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr',
    alignItems: 'center',
    gap: '8px',
  },
  settingLabel: {
    fontSize: '12px',
    color: '#5c5c65',
  },
  divider: {
    height: '1px',
    backgroundColor: '#e8e6e3',
    margin: '2px 0',
  },
  // Summary
  summaryTable: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '6px 12px',
  },
  summaryItem: {
    fontSize: '12px',
    color: '#323130',
  },
  summaryKey: {
    fontSize: '11px',
    color: '#8e8e96',
    marginBottom: '1px',
  },
  summaryVal: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#1B1B1F',
  },
  signalBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600',
    marginBottom: '8px',
  },
  emptyChart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    height: '180px',
    margin: '0 16px 16px',
    backgroundColor: '#f6f6f8',
    borderRadius: '6px',
    border: '1px dashed #d0ceca',
    color: '#8e8e96',
    fontSize: '13px',
  },
  annotBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 12px',
    margin: '0 16px',
    backgroundColor: '#fdf8ee',
    borderRadius: '4px',
    border: '1px solid #e8d5a8',
  },
  annotBarLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#7a5c1e',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  annotList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    padding: '0 16px',
  },
  annotItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 10px',
    backgroundColor: '#fdf8ee',
    borderRadius: '4px',
    fontSize: '12px',
  },
  annotItemText: {
    flex: 1,
    color: '#5c5c65',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '14px 16px',
    borderTop: '1px solid #e8e6e3',
    marginTop: 'auto',
  },
  error: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    margin: '0 16px',
    padding: '8px 12px',
    backgroundColor: '#fdf2f2',
    color: '#c4314b',
    borderRadius: '4px',
    border: '1px solid #f0c8c8',
    fontSize: '12px',
    lineHeight: '1.4',
  },
});
