import { makeStyles } from '@fluentui/react-components';
import { qikit } from '../../theme/tokens';

// All colors/fonts/radii come from the qikit design tokens (src/theme/tokens.ts).

export const useSpcStyles = makeStyles({
  panel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    overflowY: 'auto',
    height: '100%',
    fontFamily: qikit.font.base,
    backgroundColor: qikit.color.surface,
  },
  section: {
    padding: '14px 16px',
    borderBottom: `1px solid ${qikit.color.border}`,
  },
  sectionLabel: {
    fontSize: '11px',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: qikit.color.textMuted,
    marginBottom: '10px',
  },
  dataSourceEmpty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    padding: '28px 16px',
    textAlign: 'center',
  },
  dataSourceIcon: {
    width: '42px',
    height: '42px',
    borderRadius: qikit.radius.lg,
    backgroundColor: qikit.color.brandTint,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: qikit.color.brand,
    fontSize: '20px',
  },
  dataSourceHint: {
    fontSize: '12px',
    color: qikit.color.textMuted,
    lineHeight: '1.4',
  },
  dataSourceBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  address: {
    flex: 1,
    fontSize: '11.5px',
    fontFamily: qikit.font.mono,
    color: qikit.color.text,
    backgroundColor: qikit.color.surfaceAlt,
    padding: '6px 10px',
    borderRadius: qikit.radius.sm,
    border: `1px solid ${qikit.color.border}`,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  colRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    marginBottom: '2px',
  },
  colLabel: {
    fontSize: '11.5px',
    fontWeight: '600',
    color: qikit.color.text,
    minWidth: '14px',
  },
  chartTypeRow: {
    display: 'flex',
    gap: '3px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  chartBtn: {
    padding: '5px 10px',
    borderRadius: qikit.radius.sm,
    border: `1px solid ${qikit.color.borderStrong}`,
    backgroundColor: qikit.color.surface,
    color: qikit.color.text,
    fontSize: '12px',
    fontWeight: '600',
    fontFamily: 'inherit',
    cursor: 'pointer',
    letterSpacing: '0.3px',
    textTransform: 'uppercase',
    transition: 'all 0.12s ease',
    '&:hover': {
      borderTopColor: qikit.color.brand,
      borderRightColor: qikit.color.brand,
      borderBottomColor: qikit.color.brand,
      borderLeftColor: qikit.color.brand,
      color: qikit.color.brandHover,
      backgroundColor: qikit.color.brandTint,
    },
  },
  chartBtnActive: {
    backgroundColor: qikit.color.brand,
    borderTopColor: qikit.color.brandPressed,
    borderRightColor: qikit.color.brandPressed,
    borderBottomColor: qikit.color.brandPressed,
    borderLeftColor: qikit.color.brandPressed,
    color: qikit.color.surface,
    boxShadow: '0 1px 2px rgba(16,124,108,0.25)',
  },
  chartBtnMore: {
    padding: '5px 10px',
    borderRadius: qikit.radius.sm,
    border: `1px dashed ${qikit.color.borderStrong}`,
    backgroundColor: 'transparent',
    color: qikit.color.textMuted,
    fontSize: '11px',
    fontWeight: '500',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 0.12s ease',
    '&:hover': {
      borderTopColor: qikit.color.brand,
      borderRightColor: qikit.color.brand,
      borderBottomColor: qikit.color.brand,
      borderLeftColor: qikit.color.brand,
      color: qikit.color.brandHover,
    },
  },
  chartMorePanel: {
    display: 'flex',
    gap: '3px',
    flexWrap: 'wrap',
    marginTop: '6px',
    paddingTop: '8px',
    borderTop: `1px solid ${qikit.color.border}`,
  },
  settingsToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '0',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '500',
    color: qikit.color.text,
    fontFamily: 'inherit',
    '&:hover': {
      color: qikit.color.brand,
    },
  },
  settingsPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '10px',
    padding: '12px',
    backgroundColor: qikit.color.surfaceAlt,
    borderRadius: qikit.radius.md,
    border: `1px solid ${qikit.color.border}`,
  },
  settingRow: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr',
    alignItems: 'center',
    gap: '8px',
  },
  settingLabel: {
    fontSize: '12px',
    color: qikit.color.text,
  },
  divider: {
    height: '1px',
    backgroundColor: qikit.color.border,
    margin: '2px 0',
  },
  // Summary
  summaryTable: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '6px 12px',
  },
  summaryItem: {
    fontSize: '12px',
    color: qikit.color.text,
  },
  summaryKey: {
    fontSize: '11px',
    color: qikit.color.textMuted,
    marginBottom: '1px',
  },
  summaryVal: {
    fontSize: '13px',
    fontWeight: '600',
    color: qikit.color.ink,
  },
  signalBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: qikit.radius.sm,
    fontSize: '12px',
    fontWeight: '600',
    marginBottom: '8px',
  },
  emptyChart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    height: '180px',
    margin: '0 16px 16px',
    backgroundColor: qikit.color.surfaceAlt,
    borderRadius: qikit.radius.md,
    border: `1px dashed ${qikit.color.borderStrong}`,
    color: qikit.color.textMuted,
    fontSize: '13px',
  },
  annotBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 12px',
    margin: '0 16px',
    backgroundColor: qikit.color.noteBg,
    borderRadius: qikit.radius.sm,
    border: `1px solid ${qikit.color.noteBorder}`,
  },
  annotBarLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: qikit.color.note,
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  annotList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    padding: '0 16px',
  },
  annotItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 10px',
    backgroundColor: qikit.color.noteBg,
    borderRadius: qikit.radius.sm,
    fontSize: '12px',
  },
  annotItemText: {
    flex: 1,
    color: qikit.color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '14px 16px',
    borderTop: `1px solid ${qikit.color.border}`,
    marginTop: 'auto',
  },
  error: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    margin: '0 16px',
    padding: '8px 12px',
    backgroundColor: qikit.color.dangerBg,
    color: qikit.color.danger,
    borderRadius: qikit.radius.sm,
    border: `1px solid ${qikit.color.dangerBorder}`,
    fontSize: '12px',
    lineHeight: '1.4',
  },
});
